version: '3.8'

services:
  postgres:
    image: postgres:16
    ports:
      - "5442:5432"
    volumes:
      - .:/var/lib/postgresql/
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

volumes:
  postgres_data:
